# For making jumps in parameter space

import numpy as np

def get_new_parameters(list_of_sigmas,list_of_recent_guesses):
    '''
    Inputs are a list of standard deviations and a list of parameter values.
    Outputs are a list of parameter values generated by an N-dimensional Gaussian.

    The generating Gaussian has a mean of list_of_recent_guesses and standard deviations of list_of_sigmas.

    Ex:
    old_guesses = [2,3]
    sigmas = [1,1]
    get_new_parameters(sigmas,old_guesses)
    
    '''
    new_guesses = [np.random.normal(point,sigma) for point,sigma in zip(list_of_recent_guesses,list_of_sigmas)]
    return new_guesses
